{
    "name": "Odoo Gmail Connector",
    'summary': """
    Sync all your Google mails in your Odoo account without any hassle by using the Ksolves Gmail Connector! This integration allows you to manage emails and data efficiently within Odoo.
    Odoo Gmail Connector,Gmail Odoo Connector,
    Email Configurator For Gmail,
    Email Configurator,
    Odoo Advance Email Configurator,
    Gmail Odoo integration,
    Odoo Gmail integration,
    Two-Way Email Sync,
    Multiple Gmail Account Integration,
    Sending Emails via User's SMTP,
    configure outgoing emails,
    Odoo Google Gmail Integration,
    Odoo integration with Google,
    Gmail Integration module,
    Odoo Google Connector
    """,
    'description': """
    Odoo Gmail Connector,
    Gmail Odoo Connector,
    Email Configurator For Gmail,
    Email Configurator,
    Odoo Advance Email Configurator,
    Gmail Odoo integration,
    Odoo Gmail integration,
    Two-Way Email Sync,
    Multiple Gmail Account Integration,
    Sending Emails via User's SMTP,
    configure outgoing emails,
    Odoo Google Gmail Integration,
    Odoo integration with Google,
    Gmail Integration module,
    Odoo Google Connector""",
    "category": "Services",
    "author": "Ksolves India Ltd.",
    'maintainer': 'Ksolves India Ltd.',
    'live_test_url': 'https://gmailconnector17demo.ksolves.net/web/login',
    'support': 'sales@ksolves.com',

    'version': '17.0.2.1.0',

    'website': 'https://store.ksolves.com/',
    "license": "OPL-1",
    'currency': 'EUR',
    'price': '135',
    'images': ['static/description/Banner.png'],
    "depends": ["base", "mail", "google_account", "auth_oauth", 'base_setup', 'google_gmail', "base_sparse_field",
                "web"],
    'external_dependencies': {
        'python': ['google', 'google-api-core', 'google-api-python-client', 'google-auth', 'google-auth-httplib2',
                   'google-auth-oauthlib', 'google-cloud-bigquery', 'google-cloud-core', 'werkzeug'],
    },
    "data": [
        "data/ks_cron.xml",
        "data/ks_queue_data.xml",
        "data/ks_queue_job_function_data.xml",
        'security/ks_res_groups.xml',
        'security/ir.model.access.csv',
        "views/ks_res_users_view.xml",
        "views/ks_general_settings_view.xml",
        "views/ks_gmail_filters_view.xml",
        "views/ks_gmail_alias_view.xml",
        "views/ks_mail_mail_view.xml",
        "views/ks_queue_job_views.xml",
        "views/ks_queue_job_channel_views.xml",
        "views/ks_queue_job_function_views.xml",
        "views/custom_email_template.xml",
        "wizards/ks_queue_jobs_to_done_views.xml",
        "wizards/ks_queue_jobs_to_cancelled_views.xml",
        "wizards/ks_queue_requeue_job_views.xml",
        "views/ks_menu_view.xml",
        "views/mail_compose_message_views.xml",

    ],
    "development_status": "Mature",
    "post_init_hook": "post_init_hook",
    'application': True,
    'installable': True,
}
