# -*- coding: utf-8 -*-

{
    'name': 'Customer Follow Up Management',
    # 'version': '17.0.2',
    'category': 'Accounting',
    'description': """This module helps to manage customer follow-ups for accounting purposes, enabling users to track overdue payments, send follow-up reminders, and maintain good customer relationships.""",
    'summary': """Manage customer follow-up tasks and notifications for accounting purposes.""",
    'author': 'Odoo Mates, Odoo S.A',
    'license': 'LGPL-3',
    'website': 'https://www.odoomates.tech',
    'depends': ['account', 'mail'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/data.xml',
        'wizard/followup_print_view.xml',
        'wizard/followup_results_view.xml',
        'views/followup_view.xml',
        'views/account_move.xml',
        'views/partners.xml',
        'views/report_followup.xml',
        'views/reports.xml',
        'views/followup_partner_view.xml',
        'report/followup_report.xml',
    ],
    'demo': ['demo/demo.xml'],
    'images': ['static/description/banner.png'],
    'auto_install': False,
    'application': True,
    'installable': True,
}
